version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

workflows:
  build_and_push:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: postfix
          tag: exporter
          context: aws-medwing
          registry-id: AWS_ACCOUNT_ID